baseURL = 'https://github.com/JulianAbaroa/Portfolio'
languageCode = 'en-us'
title = 'Julián Abaroa - Portfolio'
theme = 'toha'

[params]
	background = "images/background.jpg"

[params.footer.navigation]
	enable = false

[params.footer.contactMe]
	enable = false

[params.footer.credentials]
	enable = true

[params.footer.newsletter]
	enable = false